<h1 class="margin-bottom">Yeni İçerik Ekle</h1>
<ol class="breadcrumb 2">
    <li>
        <a href="/yonetim"><i class="fa-home"></i>Gösterge Paneli</a>
    </li>
    <li>

        <a href="/yonetim/icerik">İçerik</a>
    </li>
    <li class="active">

        <strong>Yeni İçerik</strong>
    </li>
</ol>

<br/>

<style>
    .ms-container .ms-list {
        width: 135px;
        height: 205px;
    }

    .post-save-changes {
        float: right;
    }

    @media screen and (max-width: 789px) {
        .post-save-changes {
            float: none;
            margin-bottom: 20px;
        }
    }
</style>

<form method="post" role="form" action="/yonetim/icerik/kaydet">
    <?php if ($this->id): ?>
        <input type="hidden" class="form-control input-lg" name="id" value="<?php echo $this->post['id']; ?>"/>
    <?php endif; ?>
    <!-- Title and Publish Buttons -->
    <div class="row">
        <div class="col-sm-2 post-save-changes">
            <button type="submit"
                    class="btn <?php echo $this->post ? 'btn-orange' : 'btn-green' ?> btn-lg btn-block btn-icon">
                <?php echo $this->post ? 'Güncelle' : 'Paylaş' ?>
                <i class="entypo-check"></i>
            </button>
        </div>

        <div class="col-sm-10">
            <input type="text" class="form-control input-lg" name="baslik" placeholder="Başlık"
                   value="<?php echo $this->post['baslik'] ? $this->post['baslik'] : ''; ?>"/>
        </div>
    </div>

    <br/>

    <!-- CKeditor - Content Editor -->
    <textarea name="icerik"
              class="form-control ckeditor"><?php echo $this->post['icerik'] ? $this->post['icerik'] : ''; ?></textarea>
    <!-- CKeditor - Son -->
    <br/>

    <!-- Metaboxes -->
    <div class="row">

        <!-- Metabox :: Publish Settings -->
        <div class="col-sm-4">

            <div class="panel panel-primary" data-collapsed="0">

                <div class="panel-heading">
                    <div class="panel-title">
                        Publish Settings
                    </div>

                    <div class="panel-options">
                        <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
                    </div>
                </div>

                <div class="panel-body">

                    <div class="checkbox checkbox-replace">
                        <input type="checkbox" id="chk-1" checked>
                        <label>Show in frontpage</label>
                    </div>

                    <br/>

                    <div class="checkbox checkbox-replace">
                        <input type="checkbox" id="chk-2" checked>
                        <label>Stick this post</label>
                    </div>

                    <br/>

                    <p>Yayın Tarihi</p>

                    <div class="row">
                        <div class="col-md-7 input-group no-margin">
                            <input class="form-control datepicker" data-format="dd MM yyyy" type="text"
                                   value="<?php echo Site_Helper::getTarih($this->post['yayin_tarihi']); ?>">

                            <div class="input-group-addon">
                                <a href="#"><i class="entypo-calendar"></i></a>
                            </div>
                        </div>
                        <div class="col-md-5 input-group no-margin">
                            <input class="form-control timepicker" data-template="dropdown" data-show-seconds="false"
                                   data-default-time="11:25 AM" data-show-meridian="false" data-minute-step="1"
                                   type="text"
                                   value="<?php echo Site_Helper::getZaman($this->post['yayin_tarihi']); ?>">

                            <div class="input-group-addon">
                                <a href="#"><i class="entypo-clock"></i></a>
                            </div>
                        </div>
                    </div>
                    <br/>

                    <p>Post Status</p>
                    <select name="durum" class="selectboxit">
                        <optgroup label="Post Status">
                            <option value="1">Publish</option>
                            <option value="2">Private</option>
                            <option value="3">Protected</option>
                            <option value="4">Scheduled</option>
                        </optgroup>
                    </select>

                </div>

            </div>

        </div>


        <!-- Metabox :: Featured Image -->
        <div class="col-sm-4">

            <div class="panel panel-primary" data-collapsed="0">

                <div class="panel-heading">
                    <div class="panel-title">
                        Featured Image
                    </div>

                    <div class="panel-options">
                        <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
                    </div>
                </div>

                <div class="panel-body">

                    <div class="fileinput fileinput-new" data-provides="fileinput">
                        <div class="fileinput-new thumbnail" style="max-width: 310px; height: 160px;"
                             data-trigger="fileinput">
                            <img src="http://placehold.it/320x160" alt="...">
                        </div>
                        <div class="fileinput-preview fileinput-exists thumbnail"
                             style="max-width: 320px; max-height: 160px"></div>
                        <div>
									<span class="btn btn-white btn-file">
										<span class="fileinput-new">Select image</span>
										<span class="fileinput-exists">Change</span>
										<input type="file" name="gorsel" accept="image/*">
									</span>
                            <a href="#" class="btn btn-orange fileinput-exists" data-dismiss="fileinput">Remove</a>
                        </div>
                    </div>

                </div>

            </div>

        </div>


        <!-- Metabox :: Categories -->
        <div class="col-sm-4">

            <div class="panel panel-primary" data-collapsed="0">

                <div class="panel-heading">
                    <div class="panel-title">
                        Categories
                    </div>

                    <div class="panel-options">
                        <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
                    </div>
                </div>

                <div class="panel-body">

                    <select multiple="multiple" name="kategori[]" class="form-control multi-select">
                        <option value="elem_1">Art</option>
                        <option value="elem_2" selected>Entertainment</option>
                        <option value="elem_3">Sports</option>
                        <option value="elem_4">Gaming</option>
                        <option value="elem_5" selected>Abstraction</option>
                        <option value="elem_6">Nature</option>
                        <option value="elem_7">Summer</option>
                        <option value="elem_8">Adventures</option>
                        <option value="elem_9">Movies</option>
                        <option value="elem_10">Music</option>
                        <option value="elem_11">Technology</option>
                    </select>

                </div>

            </div>

        </div>

        <div class="clear"></div>

        <!-- Metabox :: Tags -->
        <div class="col-sm-12">

            <div class="panel panel-primary" data-collapsed="0">

                <div class="panel-heading">
                    <div class="panel-title">
                        Tags
                    </div>

                    <div class="panel-options">
                        <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
                    </div>
                </div>

                <div class="panel-body">

                    <p>Add Post Tags</p>
                    <input type="text" value="weekend,friday,happy,awesome,chill,healthy"
                           class="form-control tagsinput"/>

                </div>

            </div>

        </div>

    </div>

</form>
