<!DOCTYPE html>
<html lang="tr">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<?php  echo $this->headMeta();?>

<meta name="author" content="Mustafa Dilaver" />
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink(); ?>

<script src="/admin/assets/js/jquery-1.11.0.min.js"></script>
<!--[if lt IE 9]><script src="/admin/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

</head>
<body class="page-body">

<div class="page-container">

    <?php echo $this->render('admin-sidebar.phtml'); ?>

    <div class="main-content">

        <?php echo $this->layout()->content;?>

<?php echo $this->render('admin-footer.phtml'); ?>