<div class="sidebar-menu">

    <div class="sidebar-menu-inner">

        <header class="logo-env">

            <!-- logo -->
            <div class="logo">
                <a href="/yonetim">
                    <img src="/admin/assets/images/logo@2x.png" width="120" alt=""/>
                </a>
            </div>

            <!-- logo collapse icon -->
            <div class="sidebar-collapse">
                <a href="#" class="sidebar-collapse-icon">
                    <!-- add class "with-animation" if you want sidebar to have animation during expanding/collapsing transition -->
                    <i class="entypo-menu"></i>
                </a>
            </div>


            <!-- open/close menu icon (do not remove if you want to enable menu on mobile devices) -->
            <div class="sidebar-mobile-menu visible-xs">
                <a href="#" class="with-animation"><!-- add class "with-animation" to support animation -->
                    <i class="entypo-menu"></i>
                </a>
            </div>

        </header>


        <ul id="main-menu" class="main-menu">
            <li>
                <a href="#">
                    <i class="entypo-gauge"></i>
                    <span class="title">Dashboard</span>
                </a>
                <ul>
                    <li>
                        <a href="/yonetim/index">
                            <span class="title">Dashboard 1</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <i class="entypo-gauge"></i>
                    <span class="title">İçerik</span>
                </a>
                <ul>
                    <li>
                        <a href="/yonetim/icerik/index">
                            <span class="title">İçerikler</span>
                        </a>
                    </li>
                    <li>
                        <a href="/yonetim/icerik/duzenle">
                            <span class="title">İçerik Ekle</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>

    </div>

</div>