<!-- Footer -->
<footer class="main">

    &copy; 2015  <a href="http://ubit.com.tr" target="_blank"><strong>UBIT</strong></a> Tarafından Hazırlanmıştır.

</footer>
</div>

</div>

<?php echo $this->headScript(); ?>
<!-- Imported styles on this page -->
<link rel="stylesheet" href="/admin/assets/js/jvectormap/jquery-jvectormap-1.2.2.css">
<link rel="stylesheet" href="/admin/assets/js/rickshaw/rickshaw.min.css">



<!-- Imported scripts on this page -->
<script src="/admin/assets/js/jquery.sparkline.min.js"></script>
<script src="/admin/assets/js/rickshaw/vendor/d3.v3.js"></script>
<script src="/admin/assets/js/rickshaw/rickshaw.min.js"></script>
<script src="/admin/assets/js/raphael-min.js"></script>
<script src="/admin/assets/js/morris.min.js"></script>

</body>
</html>